FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PORT 8080

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput

# Expose the port for Cloud Run
EXPOSE 8080

# Start the Django app  
CMD gunicorn eas_inventory_system.wsgi:application --bind 0.0.0.0:$PORT
